name: SBOM and Vulnerability Scan
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sbom_and_scan:
    name: Generate SBOM with Syft and Scan with Grype
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker image
      run: |
        docker build -t flask-app:latest .

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM using Syft
      run: |
        syft flask-app:latest -o cyclonedx-json > sbom.json
        echo "SBOM generated and saved to sbom.json"

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.json

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan for vulnerabilities using Grype
      run: |
        grype sbom:sbom.json --output table

    - name: Fail on Critical Vulnerabilities
      run: |
        grype sbom:sbom.json -o json > grype-report.json
        CRITICAL_COUNT=$(jq '[.matches[] | select(.vulnerability.severity == "Critical")] | length' grype-report.json)
        echo "Critical vulnerabilities found: $CRITICAL_COUNT"
        if [ "$CRITICAL_COUNT" -gt 0 ]; then
          echo "Failing the pipeline due to critical vulnerabilities"
          exit 1
        fi
